name: cantapp
description: un'applicazione dedicata ai canti liturgici.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.2+17 #1.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0" #before >=2.1.0 <3.0.0

dependencies:
  flutter:
    sdk: flutter
  # Add the dependency for the Firebase Core Flutter SDK
  firebase_core: ^1.10.6
  firebase_analytics: ^9.0.4
  firebase_crashlytics: ^2.4.4
  firebase_auth: ^3.3.4
  firebase_in_app_messaging: ^0.6.0+5
  cloud_firestore: ^3.1.5

  # Add the dependency for adb mob, set key for iOS and Android
  # firebase_admob: ^0.10.2
  google_mobile_ads: ^1.0.1
  # Tracking Trasparency for admob
  app_tracking_transparency: ^2.0.2+1

  # Full text search algolia
  # algolia: ^1.0.1

  # Connection state
  # connectivity_wrapper: ^1.0.6

  # service locator
  # get_it: ^5.0.1

  # bloc
  flutter_bloc: ^8.0.1
  bloc_concurrency: ^0.2.0 

  # rxdart reactive ui
  rxdart: ^0.27.3

  # manager form
  formz: ^0.3.2
  

  # Non ho inserito il numero di versione, nella speranza che siano compatibili
  # Avere sempre un riguardo particolare a questi pacchetti
  equatable:
  provider:
  http:
  sqflite:
  path:
  shared_preferences:
  url_launcher:
  package_info:


  font_awesome_flutter: ^9.0.0
  #flutter_slidable: ^0.5.3
  #bubble_bottom_bar: ^1.2.0
  # settings_ui: ^1.0.0
  # flutter_svg:
  shimmer: ^2.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # In app review
  in_app_review: ^2.0.3

  # packages repository
  authentication_repository:
    path: packages/authentication_repository

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: ^0.9.0
 
    
flutter_icons:
  image_path_ios: "assets/icon/icon_ios.jpg"
  image_path_android: "assets/icon/icon_android.png"
  android: true 
  ios: true
  adaptive_icon_background: "assets/icon/icon_android_background.png"
  adaptive_icon_foreground: "assets/icon/icon_android.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    # - icons/new.png
    # - icons/plant_tree.png
    # - icons/popularity.png
    # - icons/constellation.png
    # - icons/music.png

    - assets/new.svg
    - assets/plant_tree.svg
    - assets/popularity.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

  # fonts:
  #   - family: Corben
  #     fonts:
  #         - asset: fonts/Corben/Corben-Bold.ttf
  #           weight: 700

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
